version: "3.8"
services:
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  ui-test:
    build:
      context: ./packages/ui-test
      dockerfile: Dockerfile
    depends_on:
      - frontend
