name: deploy_eks
description: 'Helm Deployment'
inputs:
  tag: 
    description: 'Commit ID'
    required: true
  repo:
    description: 'Repo name'
    required: true
  valuefile:
    description: 'Value File Path'
    required: true
  release:
    description: 'Release name'
    required: true
  namespace:
    description: 'namespace name'
    required: true
  chart:
    description: chart working directory
    required: true
  # aws_secret:
  #   description: AWS secret
  #   required: true
runs:
  using: "composite"
  steps:
    - name: Mimic Helm Deploy
      working-directory: ${{ inputs.chart }}
      shell: bash
      # env:
      #   AWS_SECRET: ${{ inputs.aws_secret }}
      #   AWS_SECRET: ${{ inputs.aws_secret }}
      run: |
        echo "Deploy Helm Chat with Below Values"
        echo "Chart path: ${{ inputs.chart }}"
        echo "Namespace: ${{ inputs.namespace }}"
        echo "Commit ID: ${{ inputs.tag }}"
        echo "Value File Path: ${{ inputs.valuefile }}"
        echo "Release name: ${{ inputs.release }}"
        echo "AWS Secret": $AWS_SECRET"