name: deploy_eks
description: 'Helm Deployment'
inputs:
  commitId: 
    description: 'Commit ID'
    required: true
  valuefile:
    description: 'Value File Path'
    required: true
  release:
    description: 'Release name'
    required: true
  working-directory:
    description: working directory
    required: true
runs:
  using: "composite"
  steps:
    - name: Mimic Helm Deploy
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        echo "Deploy Helm Chat with Below Values"
        echo "Namespace: ${{ inputs.namespace }}"
        echo "Commit ID: ${{ inputs.commitId }}"
        echo "Value File Path: ${{ inputs.valuefile }}"
        echo "Release name: ${{ inputs.release }}"