name: deploy_eks
description: 'Helm Deployment'
inputs:
  tag: 
    description: 'Commit ID'
    required: true
  repo:
    description: 'Repo name'
    required: true
  valuefile:
    description: 'Value File Path'
    required: true
  release:
    description: 'Release name'
    required: true
  namespace:
    description: 'namespace name'
    required: true
  chart:
    description: chart working directory
    required: true
  username:
    description: DOCKERHUB_USERNAME
    required: true
  token:
    description: DOCKERHUB_TOKEN
    required: true
runs:
  using: "composite"
  steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}
    - name: Docker pull
      shell: bash
      run: docker pull keweizhang/backend
    - name: Mimic Helm Deploy
      working-directory: ${{ inputs.chart }}
      shell: bash
      # env:
      run: |
        if (( $RANDOM % 2 == 0 )); then
          echo "Simulated Failure"
          exit 1
        else
          echo "Continuing with normal execution simulation"
          sleep 60
        fi
        # if [[ ${{ inputs.release }} == "scripts" ]]
        # then
        #   echo "Deploy scripts with v1"
        # else
        #   # adding comments testing
        #   echo "Deploy Helm Chat with Below Values"
        #   echo "Chart path: ${{ inputs.chart }}"
        #   echo "Namespace: ${{ inputs.namespace }}"
        #   echo "Commit ID: ${{ inputs.tag }}"
        #   echo "Value File Path: ${{ inputs.valuefile }}"
        #   echo "Release name: ${{ inputs.release }}"
        #   echo "AWS Secret: $AWS_SECRET"
        # fi