name: deploy_eks
description: 'Helm Deployment'
inputs:
  tag: 
    description: 'Commit ID'
    required: true
  repo:
    description: 'Repo name'
    required: true
  valuefile:
    description: 'Value File Path'
    required: true
  release:
    description: 'Release name'
    required: true
  namespace:
    description: 'namespace name'
    required: true
  chart:
    description: chart working directory
    required: true
  DOCKERHUB_USERNAME:
    description: DOCKERHUB_USERNAME
    required: true
  DOCKERHUB_TOKEN:
    description: DOCKERHUB_TOKEN
    required: true
runs:
  using: "composite"
  steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      env:
        DOCKERHUB_USERNAME: ${{ inputs.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ inputs.DOCKERHUB_TOKEN }}
      with:
        username: $DOCKERHUB_USERNAME
        password: $DOCKERHUB_TOKEN
    - name: Docker pull
      shell: bash
      run: docker pull kewezhang/backend
    - name: Mimic Helm Deploy
      working-directory: ${{ inputs.chart }}
      shell: bash
      # env:
      #   AWS_SECRET: ${{ inputs.aws_secret }}
      #   AWS_SECRET: ${{ inputs.aws_secret }}
      run: |
        echo "Deploy Helm Chat with Below Values"
        echo "Chart path: ${{ inputs.chart }}"
        echo "Namespace: ${{ inputs.namespace }}"
        echo "Commit ID: ${{ inputs.tag }}"
        echo "Value File Path: ${{ inputs.valuefile }}"
        echo "Release name: ${{ inputs.release }}"
        echo "AWS Secret: $AWS_SECRET"