name: 'wait for workflow runs'
description: |
  This action will wait for any previous runs of the named workflow and
  supplied run number to complete before returning.
inputs:
  run:
    description: 'Workflow run number'
    default: ${{ github.run_number }}
    required: true
  github-token:
    description: 'GitHub access token to perform API calls'
    required: true
runs:
  using: 'composite'
  steps:
  - id: poll
    shell: bash
    env:
      GITHUB_TOKEN: ${{ inputs.github-token }}
    run: |-
      check_runs() {
        actual_status=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${GITHUB_REPOSITORY}/actions/runs/${{ inputs.run }} | jq -r '.status')
        echo "Current status: $actual_status"
        if [[ "$actual_status" == "queued" ]] || [[ "$actual_status" == "in_progress" ]] || [[ "$actual_status" == "waiting" ]]; then
          return 0
        else
          return 1
        fi
      }

      while { check_runs }
      do
        echo "Waiting 5 seconds before checking queue position again..."
        sleep 5
      done
      echo "There are no runs waiting or running, continuing..."