name: approve_all_workflow
on:
   workflow_dispatch:
    inputs:
      commitId:
        description: commit id
        required: true
jobs:
  get_approval_commands:
    runs-on: ubuntu-latest
    steps:
      - name: find all waiting pipelines
        run: |
          echo "Pre-req: Run Below command to install gh deploy extention to approve workflow"
          echo "gh extension install yuri-1987/gh-deploy"
          echo "Run below commands to approve all deployments:"
          for build in $(gh workflow list --all -R $OWNER/$REPO | grep -E '\brelease' | awk '{print $1}'); 
          do 
            RUN_ID=$(gh run list -R $OWNER/$REPO -w $build --json name,headSha,status,url,databaseId --jq '.[] | select((.headSha == '\"${{ inputs.commitId }}\"') and (.status == "waiting")) | .databaseId')
            [[ ! -z "$RUN_ID" ]] && echo "gh deploy --env Production --run-id $RUN_ID --repo $OWNER/$REPO --approve"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
  