name: deploy_backend_service_1

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Image tag or commit SHA
        required: true
  workflow_run:
    workflows:
      - deploy_all
    types:
      - requested

jobs:
  deploy_to_mainnet:
    name: Deploy to Mainnet
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout Code
      #   uses: actions/checkout@v3
      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: Build KZSandbox Docker Image
          ref: ${{ github.sha }}
      - name: Deploy to EKS
        uses: ./.github/actions/deploy_eks
        with:
          tag: ${{ inputs.tag || github.event.workflow_run.head_commit.id }}
          namespace: namespace1
          release: release1
          valuefile: release1_value.yaml
          chart: js/packages/backend
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          token: ${{ secrets.DOCKERHUB_TOKEN }}
