name: deploy_all
on: 
  push:
    branches: [master]
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: js/packages/backend

jobs:
  build_docker_image:
    name: Build KZSandbox Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v3
        name: Build Image
        with:
          context: .
          file: js/packages/backend/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            keweizhang/backend
      - name: Save image_tag
        run: |
          image_tag="${{ github.sha }}"
          echo "IMAGE_TAG=$image_tag" >> $GITHUB_OUTPUT
          echo "$image_tag" > image_tag.txt
      - name: Upload image_tag artifact
        uses: actions/upload-artifact@v4
        with:
          name: image_tag
          path: js/packages/backend/image_tag.txt
      # - name: simulate long build 
      #   run: sleep 90
  # deploy_all_devnet:
  #   name: Deploy to Devnet
  #   needs: [build_docker_image]
  #   uses: kewei5zhang/kzsandbox/.github/workflows/deploy_all_devnet.yml@master
  # deploy_all_canary:
  #   name: Deploy to Canary
  #   needs: [build_docker_image]
  #   uses: kewei5zhang/kzsandbox/.github/workflows/deploy_all_canary.yml@master
  deploy_all_mainnet:
    name: Deploy All to Mainnet
    needs: [build_docker_image]
    uses: kewei5zhang/kzsandbox/.github/workflows/deploy_all_mainnet.yml@master
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}