name: deploy_backend_service_1

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Image tag or commit SHA
        required: true
  workflow_run:
    workflows:
      - deploy_all
    types:
      - requested

jobs:
  deploy_to_mainnet:
    name: Deploy to Mainnet
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout Code
      #   uses: actions/checkout@v3
      - name: Wait for Image Build
        shell: bash
        run: |
          WAIT_TIME=0
          until false;
          do
            if [[ $WAIT_TIME -gt 120 ]];
            then
              echo "❌ Waiting for image build timeout! megabackend:${{ inputs.tag || github.event.workflow_run.head_commit.id }}"
              exit 1
            fi
            echo "🌀 Waiting image build megabackend:${{ inputs.tag || github.event.workflow_run.head_commit.id }}. Checking every 30s..."
            sleep 30; ((WAIT_TIME++))
          done
          echo "✅ Found image tag ${{ inputs.tag }} in repo ${{ inputs.repo }}."
      - name: Deploy to EKS
        uses: ./.github/actions/deploy_eks
        with:
          tag: ${{ inputs.tag || github.event.workflow_run.head_commit.id }}
          namespace: namespace1
          release: release1
          valuefile: release1_value.yaml
          chart: js/packages/backend
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          token: ${{ secrets.DOCKERHUB_TOKEN }}
