name: release_all
on: [push]

defaults:
  run:
    shell: bash
    working-directory: js/packages/backend

jobs:
  build_builder_image:
    name: Update docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v3
        name: Build Image
        with:
          context: .
          file: builder.Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            keweizhang/builder
  deploy_all_to_devnet:
    name: Deploy to Devnet
    needs: [build_runner_image]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - release: acct-broker
            valuefile: ./devnet/acct-broker-values.yaml
          - release: acct-backfill-broker
            valuefile: ./devnet/acct-backfill-broker-values.yaml
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Deploy to EKS
        uses: ./.github/actions/deploy_eks
        with:
          tag: ${{ github.sha }}
          namespace: indexing-devnet
          release: ${{ matrix.release }}
          valuefile: ${{ matrix.valuefile }}
          working-directory: js/packages/backend
  deploy_cf_to_devnet:
    name: Deploy to Frontend Devnet
    needs: [deploy_all_to_devnet]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Mimic Deployment
      run: |
        echo "Deploying Frontend Devnet..."
  deploy_all_to_canary:
    name: Deploy to Canary
    needs: [build_runner_image]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - release: acct-broker
            valuefile: ./mainnet/acct-broker-values.yaml
          - release: acct-backfill-broker
            valuefile: ./mainnet/acct-backfill-broker-values.yaml
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Deploy to EKS
        uses: ./.github/actions/deploy_eks
        with:
          tag: ${{ github.sha }}
          namespace: indexing-mainnet
          release: ${{ matrix.release }}
          valuefile: ${{ matrix.valuefile }}
          working-directory: js/packages/backend
  deploy_cf_to_canary:
    name: Deploy to Frontend Canary
    needs: [deploy_all_to_canary]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Mimic Deployment
      run: |
        echo "Deploying Frontend Canary ..."
  deploy_all_to_mainnet:
    name: Deploy All to Mainnet
    needs: [publish_docker_image]
    uses: kewei5zhang/kzsandbox/.github/workflows/deploy_all_mainnet.yml@main