name: release_frontend
on: [push]

jobs:
  deploy_to_frontend_devnet:
    name: Deploy to Frontend Devnet
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Wait for tests to succeed
      uses: lewagon/wait-on-check-action@v1.0.0
      with:
        ref: ${{ github.ref }}
        check-name: 'Deploy to Devnet'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10
        allowed-conclusions: success,skipped,cancelled
    - name: Mimic Deployment
      run: |
        echo "Deploying Devnet..."
  deploy_to_frontend_canary:
    name: Deploy to Frontend Canary
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Wait for tests to succeed
      uses: lewagon/wait-on-check-action@v1.0.0
      with:
        ref: ${{ github.ref }}
        check-name: 'Deploy to Canary'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10
        allowed-conclusions: success,skipped,cancelled
    - name: Mimic Deployment
      run: |
        echo "Deploying Canary ..."
  deploy_to_frontend_mainnet:
    name: Deploy to Frontend Mainnet
    runs-on: ubuntu-latest
    needs: [deploy_to_frontend_devnet,deploy_to_frontend_canary]
    environment: Production
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Wait for tests to succeed
      uses: lewagon/wait-on-check-action@v1.0.0
      with:
        ref: ${{ github.ref }}
        check-name: 'Deploy to Mainnet'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10
        allowed-conclusions: success,skipped,cancelled
    - name: Mimic Deployment
      run: |
        echo "Deploying Mainnet ..."