name: rollback_all

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Image tag or commit SHA
        required: true
  workflow_run:
    workflows:
      - release_all
    types:
      - requested

jobs:
  deploy_all_to_mainnet:
    name: Deploy to Mainnet
    runs-on: ubuntu-latest
    environment: Production
    strategy:
      matrix:
        include:
          - release: acct-broker
            valuefile: ./mainnet/acct-broker-values.yaml
          - release: acct-backfill-broker
            valuefile: ./mainnet/acct-backfill-broker-values.yaml
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Wait for build to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.event.inputs.tag || github.event.workflow_run.head_commit.id }}
          check-name: 'Release all - Build Docker Image' # The same name as docker build job in release_all
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success,skipped
      - name: Deploy to EKS
        uses: ./.github/actions/deploy_eks
        with:
          tag: ${{ github.event.inputs.tag || github.event.workflow_run.head_commit.id }}
          namespace: indexing-mainnet
          release: ${{ matrix.release }}
          valuefile: ${{ matrix.valuefile }}
          working-directory: js/packages/backend
  deploy_to_frontend_mainnet:
    name: Deploy to Frontend Mainnet
    runs-on: ubuntu-latest
    needs: [deploy_all_to_mainnet]
    environment: Production
    steps:
    - uses: actions/checkout@v3
    - name: Mimic Deployment
      run: |
        echo "Deploying Mainnet ..."